title = "Api GateWay"

[server]
ip = "0.0.0.0"
port = 9999

[logger]
# file_path = "./log/apigateway_log.txt"
file_path = "null"
log_level = "info"

# Outer to Browser
# Inner to Backend 

[outer_api]
classification = "/classification"
label = "/label"


[inner_api]
url = "127.0.0.1"
port = 5000
classification = "/classification"
label = "/label"

